### ISSUE TITLE
Add timeout for jubilee

### ISSUE THREAD

**Issue by jonathantneal** [chapmanu/web-components#15]
**Steps to reproduce:**

- Take a moment to appreciate @bcole808 and all he does for @chapmanu.
- Close a free issue and feel both productive and successful.
- Politely request that, in the future, reporter file fun and/or festive issues outside GitHub (optional)
- Learn something new about Hawaii. For instance, they are the only state whose state gem is technically an animal.

Reporter requests this issue be resolved by EOD Dec 30, annually.

**Comment by bcole808** [comment]
Only one day back in the office and I'm already resolving issues. Wohooo, productivity!

![s2vnl](https://cloud.githubusercontent.com/assets/5074711/5620764/ba356fce-94e3-11e4-99e5-bfb19eb3e977.jpg)
